#!/bin/bash
# Sat Feb 10 2018 14:58 : cicero44bc

printf "This script takes a clean install of Debian 9.3 and adds apt repositories,\ndownloads packages, wallpapers, enables gnome extensions and sets preferences\nsuch as wallpapers and gnome preferences. Full details are available by reading\nthe script.\n\nCurrently you need to install sudo and add user to sudoers before running with\nsudo to work.\n\n All is on one line for easy editing.\n"
read -r -p "Happy to run? [Y/n] " input

case $input in
    [yY][eE][sS]|[yY])
 echo "Hold on to your butts..."
 echo "Adding non-free and contrib repos (UK)"
 sudo su -c "echo 'deb http://ftp.uk.debian.org/debian/ stretch main contrib non-free' > /etc/apt/sources.list.d/debnonfree.list"
 sudo su -c "echo 'deb-src http://ftp.uk.debian.org/debian/ stretch main contrib non-free' > /etc/apt/sources.list.d/debnonfree.list"
 echo "Updating apt"
 sudo apt update
 echo "Running apt upgrade"
 sudo apt upgrade -y
 sudo apt update
 sudo apt dist-upgrade -y
 sudo apt update
 echo "Installing curl"
 sudo apt install curl -y
 echo "Installing apt-transport-https"
 sudo apt install apt-transport-https -y
 echo "Installing required intel wifi components"
 sudo apt install firmware-iwlwifi -y
 echo "Installing atom gpgkey and installing atom"
 curl -L https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -;sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list';sudo apt update;sudo apt install atom -y
 echo "Adding backports, updating apt and installing virtualbox"
 sudo su -c "echo 'deb http://ftp.uk.debian.org/debian stretch-backports main contrib non-free' > /etc/apt/sources.list.d/debianbackports.list"; sudo apt update; sudo apt install virtualbox -y
 echo "Installing git"
 sudo apt install git -y
 echo "Installing utils"
 sudo apt install lshw htop glances expect sshfs aria2 screenfetch pv thefuck sqlitebrowser iotop iftop screen gparted inxi hdparm gconf2 gconf-service libgtk2.0-0 libudev1 libgcrypt20 libnotify4 libxtst6 libnss3 python gvfs-bin xdg-utils libcap2 bluetooth -y
 echo "Installing tor"
 sudo su -c "apt install torbrowser-launcher -t stretch-backports"
 echo "Installing VLC"
 sudo apt install vlc browser-plugin-vlc -y
 echo "Installing handbrake & decoders"
 sudo apt install handbrake libdvd-pkg libaacs0 libbluray-bdj libbluray1 -y
 echo "Installing dropbox and nautilus components"
 wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
 .dropbox-dist/dropboxd
 sudo apt install nautilus-dropbox
 #ADD HERE: openvpn and homeconnection
 echo 'Installing openvpn & pptp & gnome components'
 sudo apt install openvpn network-manager-openvpn-gnome pptp-linux network-manager-pptp network-manager-pptp-gnome
 echo 'Installing deluge'
 sudo apt install deluge
 echo 'Installing wxhexeditor'
 sudo apt install wxhexeditor
 echo 'All installed, enjoy.'
;;

    [nN][oO]|[nN])
 echo "No problem, exiting."
       ;;

    *)
 echo "Invalid input..."
 exit 1
 ;;
esac
